=== nrad/Pythonia/Cable/cabel-0.85/modules/modul.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Matthias (paprosoft) --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">	<xs:element name="modul">		<xs:annotation>			<xs:documentation>encapsulates a modul</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:sequence>				<xs:element name="input" minOccurs="0">					<xs:complexType>						<xs:sequence minOccurs="0" maxOccurs="unbounded">							<xs:element ref="vardef" minOccurs="0" maxOccurs="unbounded"/>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="output" minOccurs="0">					<xs:complexType>						<xs:sequence minOccurs="0" maxOccurs="unbounded">							<xs:element ref="vardef" minOccurs="0" maxOccurs="unbounded"/>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="global" minOccurs="0">					<xs:complexType>						<xs:sequence minOccurs="0">							<xs:element name="def" minOccurs="0" maxOccurs="unbounded">								<xs:complexType>									<xs:simpleContent>										<xs:extension base="xs:string">											<xs:attribute name="description" type="xs:string" use="optional"/>										</xs:extension>									</xs:simpleContent>								</xs:complexType>							</xs:element>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element ref="opcode" minOccurs="0"/>			</xs:sequence>			<xs:attribute name="file" type="xs:string" use="optional"/>			<xs:attribute ref="name" type="xs:string" use="required"/>			<xs:attribute ref="widget" use="optional"/>			<xs:attribute ref="description" use="required"/>			<xs:attribute name="skin" type="xs:string" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="input">		<xs:annotation>			<xs:documentation>encapsulates all input params</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:sequence minOccurs="0" maxOccurs="unbounded">				<xs:element ref="varref" minOccurs="0" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="output">		<xs:annotation>			<xs:documentation>encapsulates all out parameters</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:choice>				<xs:element name="vardef" minOccurs="0">					<xs:complexType>						<xs:attribute name="name" type="xs:ID" use="required"/>						<xs:attribute name="csType" use="optional">							<xs:simpleType>								<xs:restriction base="xs:string">									<xs:enumeration value="i"/>									<xs:enumeration value="a"/>									<xs:enumeration value="k"/>									<xs:enumeration value="gi"/>									<xs:enumeration value="ga"/>									<xs:enumeration value="gk"/>									<xs:enumeration value="p"/>									<xs:enumeration value="v"/>									<xs:enumeration value="w"/>									<xs:enumeration value="c"/>									<xs:enumeration value="f"/>									<xs:enumeration value="gv"/>									<xs:enumeration value="fa"/>									<xs:enumeration value="reserved_symbol"/>								</xs:restriction>							</xs:simpleType>						</xs:attribute>						<xs:attribute name="description" type="xs:string" use="optional"/>					</xs:complexType>				</xs:element>				<xs:element ref="varref" minOccurs="0"/>			</xs:choice>		</xs:complexType>	</xs:element>	<xs:element name="opcode">		<xs:annotation>			<xs:documentation>calls a CSound "function"</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:simpleContent>				<xs:extension base="xs:string"/>			</xs:simpleContent>		</xs:complexType>	</xs:element>	<xs:element name="vardef">		<xs:annotation>			<xs:documentation>defines a var</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:attribute ref="name" use="required"/>			<xs:attribute name="widget" use="optional">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="defSlider"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>			<xs:attribute name="scoParam" type="xs:int" use="optional"/>			<xs:attribute name="value" type="xs:string" use="optional"/>			<xs:attribute name="min" type="xs:integer" use="optional"/>			<xs:attribute name="max" type="xs:integer" use="optional"/>			<xs:attribute ref="description" use="optional"/>			<xs:attribute name="isModulPort" type="xs:boolean" use="optional" default="1"/>			<xs:attribute name="csType" use="required">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="i"/>						<xs:enumeration value="a"/>						<xs:enumeration value="k"/>						<xs:enumeration value="gi"/>						<xs:enumeration value="ga"/>						<xs:enumeration value="gk"/>						<xs:enumeration value="p"/>						<xs:enumeration value="v"/>						<xs:enumeration value="w"/>						<xs:enumeration value="c"/>						<xs:enumeration value="f"/>						<xs:enumeration value="gv"/>						<xs:enumeration value="fa"/>						<xs:enumeration value="reserved_symbol"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>		</xs:complexType>	</xs:element>	<xs:element name="varref">		<xs:annotation>			<xs:documentation>references a var</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:attribute name="ref" type="xs:IDREF" use="required"/>		</xs:complexType>	</xs:element>	<xs:attribute name="widget">		<xs:annotation>			<xs:documentation>defines the widget to use for the graphical representation of the i/o params</xs:documentation>		</xs:annotation>		<xs:simpleType>			<xs:restriction base="xs:string">				<xs:enumeration value="defSlidebars"/>				<xs:enumeration value="defModulBox"/>			</xs:restriction>		</xs:simpleType>	</xs:attribute>	<xs:attribute name="name" type="xs:ID">		<xs:annotation>			<xs:documentation>unique name</xs:documentation>		</xs:annotation>	</xs:attribute>	<xs:attribute name="description" type="xs:string">		<xs:annotation>			<xs:documentation>describes the modul, var, or what it should describe.oh my god</xs:documentation>		</xs:annotation>	</xs:attribute>	<xs:attribute name="moduleID" type="xs:string">		<xs:annotation>			<xs:documentation>reference to the module to which the node belongs</xs:documentation>		</xs:annotation>	</xs:attribute></xs:schema>

=== nrad/Pythonia/Cable/cabel-0.85/modules/control/MidiNoteIn.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="MidiNoteIn" description="Midi input of frequency, note number, velocity and channel aftertouch">
  <input>
    <vardef name="velscale" csType="i" value="15000" min="0" max="32000" description="Scaling of MIDI velocity"/>
    <vardef name="minafttch" csType="i" value="0" description="Minimal value for scaled channel aftertouch"/>
    <vardef name="maxafttch" csType="i" value="127" description="Maximal value for scaled channel aftertouch"/>
  </input>
  <output>
    <vardef name="frq" csType="k" description="Frequency of MIDI note with pitch bend information"/>
    <vardef name="note" csType="k" description="MIDI note number of last pressed key"/>
    <vardef name="vel" csType="i" description="Velocity of MIDI note"/>
    <vardef name="afttch" csType="k" description="Scaled channel aftertouch"/>
  </output>
  <opcode>/* Midi keyboard input of note number and velocity */
opcode MidiNoteIn, kkik, iii
  ivelscale, iminafttch, imaxafttch xin

  knote init 0
  kvel init 0
  kafttch init 0

  midinoteonkey knote, kvel
  midichannelaftertouch kafttch, iminafttch, imaxafttch
  kfrq cpsmidib
  ivel ampmidi  ivelscale

  xout kfrq, knote, ivel, kafttch
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/sequencing/Sequencer.xml
<?xml version="1.0" encoding="UTF-8"?><modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="Sequencer" description="Analog style 8 step sequencer">  <input>    <vardef name="step" csType="k" value="1" min="0" max="1" digits="0" description="Trigger or clock signal" />    <vardef name="reset" csType="k" value="0" min="0" max="1" digits="0" description="Resets to val1" />    <vardef name="steps" csType="k" value="8" min="1" max="8" digits="0" description="Number of steps" />    <vardef name="val1" csType="k" value="60" min="0" max="127" digits="0" description="Value for step 1" />    <vardef name="val2" csType="k" value="61" min="0" max="127" digits="0" description="Value for step 2" />    <vardef name="val3" csType="k" value="62" min="0" max="127" digits="0" description="Value for step 3" />    <vardef name="val4" csType="k" value="63" min="0" max="127" digits="0" description="Value for step 4" />    <vardef name="val5" csType="k" value="64" min="0" max="127" digits="0" description="Value for step 5" />    <vardef name="val6" csType="k" value="65" min="0" max="127" digits="0" description="Value for step 6" />    <vardef name="val7" csType="k" value="66" min="0" max="127" digits="0" description="Value for step 7" />    <vardef name="val8" csType="k" value="67" min="0" max="127" digits="0" description="Value for step 8" />  </input>  <output>    <vardef name="out" csType="k" description="Output value"/>    <vardef name="gate" csType="k" description="Gate signal if val is not 0"/>  </output>  <opcode>/* Analog style 8 step sequencer */opcode Sequencer, kk, kkkkkkkkkkk  kstep, kreset, ksteps, kval1, kval2, kval3, kval4, kval5, kval6, kval7, kval8 xin  kclock     init  0  klaststep  init  0  klastreset init  0  kstep    limit     kstep, 0, 1  kreset   limit     kreset, 0, 1  ksteps   limit     ksteps, 1, 8  ksteps   =         int(ksteps)  kval1   limit     kval1, 0, 127  kval1   =         int(kval1)  kval2   limit     kval2, 0, 127  kval2   =         int(kval2)  kval3   limit     kval3, 0, 127  kval3   =         int(kval3)  kval4   limit     kval4, 0, 127  kval4   =         int(kval4)  kval5   limit     kval5, 0, 127  kval5   =         int(kval5)  kval6   limit     kval6, 0, 127  kval6   =         int(kval6)  kval7   limit     kval7, 0, 127  kval7   =         int(kval7)  kval8   limit     kval8, 0, 127  kval8   =         int(kval8)  if (kclock == 1) then    kval = kval1  elseif (kclock == 2) then    kval = kval2  elseif (kclock == 3) then    kval = kval3  elseif (kclock == 4) then    kval = kval4  elseif (kclock == 5) then    kval = kval5  elseif (kclock == 6) then    kval = kval6  elseif (kclock == 7) then    kval = kval7  elseif (kclock == 8) then    kval = kval8  endif    if (klaststep == 0 &amp;&amp; kstep == 1) then    kclock = kclock + 1  endif  if (kclock == ksteps+1) then    kclock = 1  endif  if (kval == 0) then    kgate = 0  else    kgate = 1  endif  if (klastreset == 0 &amp;&amp; kreset == 1) then    kclock = 1  endif  klaststep = kstep  klastreset = kreset  xout kval, kgateendop  </opcode></modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/amps mixers/Panning.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="Panning" description="Pan input signal between the two outputs">
  <input>
    <vardef name="in" csType="a" description="Audio rate signal"/>
    <vardef name="pan" csType="k" value="0" min="0" max="1" description="Pan in between out1 (pan=0) and out2 (pan=1)"/>
  </input>
  <output>
    <vardef name="out1" csType="a" description="First audio output"/>
    <vardef name="out2" csType="a" description="Second audio output"/>
  </output>
  <opcode>/* Pan input signal between the two outputs */
opcode Panning, aa, ak
  ain, kpan  xin
  kpan  limit  kpan, 0, 1
  aout1 = ain*(1-kpan)
  aout2 = ain*kpan
  xout aout1, aout2
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/modulators/SineLfo.xml
<?xml version="1.0" encoding="UTF-8"?><modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="SineLfo" description="Sine low frequency oscillator">  <input>    <vardef name="frq" csType="k" value="1" min="0" max="100" description="Frequency of LFO"/>    <vardef name="amp" csType="k" value="1" min="0" description="Amplitude of LFO"/>    <vardef name="phi" csType="i" value="0" min="-0.001" max="1" digits="3" description="Initial phase of LFO (negativ to skip initialisation)"/>  </input>  <output>    <vardef name="out" csType="k" description="Output of LFO"/>  </output>  <global>    <def description="Sine table">gisinelfo   ftgen  0, 0, 2048, 10 ,1</def>  </global>  <opcode>/* Sine low frequency oscillator */opcode SineLfo, k, kki  kfrq, kamp, iphi xin  kfrq     limit      kfrq, 0, 100  kamp     limit      kamp, 0, 50000  iphi     limit      iphi, -1, 1  kout     oscil      kamp, kfrq, gisinelfo, iphi  xout koutendop  </opcode></modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/filters/MoogVcf2.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="MoogVcf2" description="Moog lowpass filter (no self-oscillation)">
  <input>
    <vardef name="in" csType="a" description="Audio rate input"/>
    <vardef name="fco" csType="k" value="2000" min="0" description="Filter cut-off frequency"/>
    <vardef name="res" csType="k" min="0" max="0.85" description="Filter resonance"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="Filtered audio signal"/>
  </output>
  <opcode>/* Moog lowpass filter */
opcode MoogVcf2, a, akk
  ain, kfco, kres  xin

  ain     = ain*0.00003
  ain     limit ain, -1, 1
  kfco    limit kfco, 0, 50000
  kres    limit kres, 0, 0.85
  aout    moogvcf ain, kfco, kres
  aout    = aout*20000

  xout aout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/effects/AnalogEcho.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="AnalogEcho" description="Reverb based on the MN3011 IC">
  <input>
    <vardef name="in" csType="a" description="Audio input"/>
    <vardef name="lvl" csType="i" value="1" min="0" max="1" description="Output level"/>
    <vardef name="delay" csType="i" value="0.5" min="0" max="1" description="Delay factor"/>
    <vardef name="fdbk" csType="i" value="0.3" min="0" max="1" description="Feedback amount"/>
    <vardef name="echo" csType="i" value="0.04" min="0" max="1" description="Reverb amount"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="Input with applied echo"/>
  </output>
  <opcode>/* Reverb based on the MN3011 IC */
opcode AnalogEcho, a, aiiii
  ain, ilvl, idelay, ifdbk, iecho  xin

  afdbk     init     0
  ain       =        ain+afdbk*ifdbk
  atemp     delayr   1
  atap1     deltapi  0.0396*idelay
  atap2     deltapi  0.0662*idelay
  atap3     deltapi  0.1194*idelay
  atap4     deltapi  0.1726*idelay
  atap5     deltapi  0.2790*idelay
  atap6     deltapi  0.3328*idelay
            delayw   ain
  afdbk     butterlp atap6, 7000
  abbd      sum      atap1, atap2, atap3, atap4, atap5, atap6
  abbd      butterlp abbd, 7000
  aout      =        (ain+abbd*iecho)*ilvl

  ; stay triggered until echo fades out
  kfade     linsegr  1, 0.01, 1, 0.33*idelay*(1+ifdbk)*(1+iecho), 0
  aout      =        aout*kfade
  
  xout aout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/modulators/SawLfo.xml
<?xml version="1.0" encoding="UTF-8"?><modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="SawLfo" description="Saw low frequency oscillator">  <input>    <vardef name="frq" csType="k" value="1" min="0" max="100" description="Frequency of LFO"/>    <vardef name="amp" csType="k" value="1" min="0" description="Amplitude of LFO"/>    <vardef name="phi" csType="i" value="0" min="-0.001" max="1" digits="3" description="Initial phase of LFO (negativ to skip initialisation)"/>  </input>  <output>    <vardef name="out" csType="k" description="Output of LFO"/>  </output>  <global>    <def description="Saw table">gisawlfo   ftgen  0, 0, 2048, 7, 1, 2048, -1</def>  </global>  <opcode>/* Saw low frequency oscillator */opcode SawLfo, k, kki  kfrq, kamp, iphi xin  kfrq     limit      kfrq, 0, 100  kamp     limit      kamp, 0, 50000  iphi     limit      iphi, -1, 1  kout     oscil      kamp, kfrq, gisawlfo, iphi  xout koutendop  </opcode></modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/control/MidiCtrlIn.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="MidiCtrlIn" description="Get scaled value from MIDI controller">
  <input>
    <vardef name="chnl" csType="i" value="1" min="1" max="16" digits="0" description="MIDI channel"/>
    <vardef name="ccnum" csType="i" value="1" min="1" max="128" digits="0" description="Controller number"/>
    <vardef name="min" value="0" csType="i" description="Minimal value for scaled controller"/>
    <vardef name="max" value="127" csType="i" description="Maximal value for scaled controller"/>
  </input>
  <output>
    <vardef name="out" csType="k" description="Scaled MIDI controller value"/>
  </output>
  <opcode>/* Get value from MIDI controller */
opcode MidiCtrlIn, k, iiii
  ichnl, iccnum, imin, imax  xin

  kout    ctrl7       ichnl, iccnum, imin, imax
  
  xout kout
endop
  </opcode>
</modul>
