=== nrad/Pythonia/Cable/cabel-0.85/modules/modul.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Matthias (paprosoft) --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">	<xs:element name="modul">		<xs:annotation>			<xs:documentation>encapsulates a modul</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:sequence>				<xs:element name="input" minOccurs="0">					<xs:complexType>						<xs:sequence minOccurs="0" maxOccurs="unbounded">							<xs:element ref="vardef" minOccurs="0" maxOccurs="unbounded"/>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="output" minOccurs="0">					<xs:complexType>						<xs:sequence minOccurs="0" maxOccurs="unbounded">							<xs:element ref="vardef" minOccurs="0" maxOccurs="unbounded"/>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="global" minOccurs="0">					<xs:complexType>						<xs:sequence minOccurs="0">							<xs:element name="def" minOccurs="0" maxOccurs="unbounded">								<xs:complexType>									<xs:simpleContent>										<xs:extension base="xs:string">											<xs:attribute name="description" type="xs:string" use="optional"/>										</xs:extension>									</xs:simpleContent>								</xs:complexType>							</xs:element>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element ref="opcode" minOccurs="0"/>			</xs:sequence>			<xs:attribute name="file" type="xs:string" use="optional"/>			<xs:attribute ref="name" type="xs:string" use="required"/>			<xs:attribute ref="widget" use="optional"/>			<xs:attribute ref="description" use="required"/>			<xs:attribute name="skin" type="xs:string" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="input">		<xs:annotation>			<xs:documentation>encapsulates all input params</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:sequence minOccurs="0" maxOccurs="unbounded">				<xs:element ref="varref" minOccurs="0" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="output">		<xs:annotation>			<xs:documentation>encapsulates all out parameters</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:choice>				<xs:element name="vardef" minOccurs="0">					<xs:complexType>						<xs:attribute name="name" type="xs:ID" use="required"/>						<xs:attribute name="csType" use="optional">							<xs:simpleType>								<xs:restriction base="xs:string">									<xs:enumeration value="i"/>									<xs:enumeration value="a"/>									<xs:enumeration value="k"/>									<xs:enumeration value="gi"/>									<xs:enumeration value="ga"/>									<xs:enumeration value="gk"/>									<xs:enumeration value="p"/>									<xs:enumeration value="v"/>									<xs:enumeration value="w"/>									<xs:enumeration value="c"/>									<xs:enumeration value="f"/>									<xs:enumeration value="gv"/>									<xs:enumeration value="fa"/>									<xs:enumeration value="reserved_symbol"/>								</xs:restriction>							</xs:simpleType>						</xs:attribute>						<xs:attribute name="description" type="xs:string" use="optional"/>					</xs:complexType>				</xs:element>				<xs:element ref="varref" minOccurs="0"/>			</xs:choice>		</xs:complexType>	</xs:element>	<xs:element name="opcode">		<xs:annotation>			<xs:documentation>calls a CSound "function"</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:simpleContent>				<xs:extension base="xs:string"/>			</xs:simpleContent>		</xs:complexType>	</xs:element>	<xs:element name="vardef">		<xs:annotation>			<xs:documentation>defines a var</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:attribute ref="name" use="required"/>			<xs:attribute name="widget" use="optional">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="defSlider"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>			<xs:attribute name="scoParam" type="xs:int" use="optional"/>			<xs:attribute name="value" type="xs:string" use="optional"/>			<xs:attribute name="min" type="xs:integer" use="optional"/>			<xs:attribute name="max" type="xs:integer" use="optional"/>			<xs:attribute ref="description" use="optional"/>			<xs:attribute name="isModulPort" type="xs:boolean" use="optional" default="1"/>			<xs:attribute name="csType" use="required">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="i"/>						<xs:enumeration value="a"/>						<xs:enumeration value="k"/>						<xs:enumeration value="gi"/>						<xs:enumeration value="ga"/>						<xs:enumeration value="gk"/>						<xs:enumeration value="p"/>						<xs:enumeration value="v"/>						<xs:enumeration value="w"/>						<xs:enumeration value="c"/>						<xs:enumeration value="f"/>						<xs:enumeration value="gv"/>						<xs:enumeration value="fa"/>						<xs:enumeration value="reserved_symbol"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>		</xs:complexType>	</xs:element>	<xs:element name="varref">		<xs:annotation>			<xs:documentation>references a var</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:attribute name="ref" type="xs:IDREF" use="required"/>		</xs:complexType>	</xs:element>	<xs:attribute name="widget">		<xs:annotation>			<xs:documentation>defines the widget to use for the graphical representation of the i/o params</xs:documentation>		</xs:annotation>		<xs:simpleType>			<xs:restriction base="xs:string">				<xs:enumeration value="defSlidebars"/>				<xs:enumeration value="defModulBox"/>			</xs:restriction>		</xs:simpleType>	</xs:attribute>	<xs:attribute name="name" type="xs:ID">		<xs:annotation>			<xs:documentation>unique name</xs:documentation>		</xs:annotation>	</xs:attribute>	<xs:attribute name="description" type="xs:string">		<xs:annotation>			<xs:documentation>describes the modul, var, or what it should describe.oh my god</xs:documentation>		</xs:annotation>	</xs:attribute>	<xs:attribute name="moduleID" type="xs:string">		<xs:annotation>			<xs:documentation>reference to the module to which the node belongs</xs:documentation>		</xs:annotation>	</xs:attribute></xs:schema>

=== nrad/Pythonia/Cable/cabel-0.85/modules/filters/ButterBr.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="ButterBr" description="A second-order band-reject Butterworth filter">
  <input>
    <vardef name="in" csType="a" description="Audio rate input"/>
    <vardef name="fcf" csType="k" value="2000" min="0" description="Filter center frequency"/>
    <vardef name="bandwidth" csType="k" value="100" min="0" description="Bandwidth of the filter"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="Filtered audio signal"/>
  </output>
  <opcode>/* Second-order Butterworth band-reject filter */
opcode ButterBr, a, akk
  ain, kfcf, kbandwidth  xin

  kfco    limit kfcf, 0, 50000
  kbandwidth limit kbandwidth, 0, 50000
  aout    butterbr ain, kfcf, kbandwidth

  xout aout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/modulators/AdsrExpMidi.xml
<?xml version="1.0" encoding="UTF-8"?><modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="AdsrExpMidi" description="MIDI activated exponential ADSR envelope">  <input>    <vardef name="amp" csType="i" value="1" description="Amplitude scale factor"/>    <vardef name="atk" csType="i" value="0.01" min="0" description="Attack time in seconds"/>    <vardef name="dec" csType="i" min="0" description="Decay time in seconds"/>    <vardef name="slev" csType="i" value="1" min="0" max="1" description="Sustain level"/>    <vardef name="rel" csType="i" value="0.01" min="0" description="Release time in seconds"/>  </input>  <output>    <vardef name="env" csType="k" description="Envelope at control rate"/>  </output>  <opcode>/* MIDI activated exponential ADSR envelope */opcode AdsrExpMidi, k, iiiii  iamp, iatk, idec, islev, irel xin  kenv     mxadsr     iatk, idec, islev, irel  kenv     =          iamp*kenv  xout kenvendop  </opcode></modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/effects/BitCrusher.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="BitCrusher" description="Bit depth / sample rate reducer">
  <input>
    <vardef name="in" csType="a" description="Audio input"/>
    <vardef name="bits" csType="i" value="16" min="1" max="16" digits="0" description="Bit depth"/>
    <vardef name="rate" csType="i" value="44100" min="1" max="48000" digits="0" description="Sample rate"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="LoFi inferno"/>
  </output>
  <opcode>/* Bit depth / sample rate reducer */
opcode BitCrusher, a, aii
  ain, ibits, irate  xin

  ibits    limit    ibits, 1, 16
  ibits    =        int(ibits)
  irate    limit    irate, 1, 48000
  irate    =        int(irate)
  
  ibits    =        2^ibits
  ifold    =        sr/irate
  
  kin      downsamp ain
  kin      =        kin+32768
  kin      =        kin*(ibits/65536)
  kin      =        int(kin)
  aout     upsamp   kin
  aout     =        aout*(65536/ibits)-32768
  aout     fold     aout, ifold
  
  xout aout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/amps mixers/Mixer2.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="Mixer2" description="Mixer for two audio signals">
  <input>
    <vardef name="in1" csType="a" description="First audio rate signal"/>
    <vardef name="gain1" csType="k" value="1" min="0" description="Amplitude multiplicator for in1"/>
    <vardef name="in2" csType="a" description="Second audio rate signal"/>
    <vardef name="gain2" csType="k" value="1" min="0" description="Amplitude multiplicator for in2"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="Mixed input signals"/>
  </output>
  <opcode>/* Mixer for two audio signals */
opcode Mixer2, a, akak
  ain1, kgain1, ain2, kgain2 xin
  aout = ain1*kgain1 + ain2*kgain2
  xout aout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/modulators/AdsrLinTrigger.xml
<?xml version="1.0" encoding="UTF-8"?><modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="AdsrLinTrigger" description="Triggered linear ADSR envelope">  <input>    <vardef name="trigger" csType="k" value="1" min="0" max="1" digits="0" description="Trigger or clock signal"/>    <vardef name="amp" csType="i" value="1" description="Amplitude scale factor"/>    <vardef name="atk" csType="i" value="0.01" min="0" max="1000" description="Attack time in seconds"/>    <vardef name="dec" csType="i" min="0" max="1000" description="Decay time in seconds"/>    <vardef name="slev" csType="i" value="1" min="0" max="1" description="Sustain level"/>    <vardef name="stime" csType="i" min="0" max="1000" description="Sustain time in seconds"/>    <vardef name="rel" csType="i" value="0.01" min="0" max="1000" description="Release time in seconds"/>  </input>  <output>    <vardef name="env" csType="k" description="Envelope control signal"/>  </output>  <opcode>/* Triggered linear ADSR envelope */opcode AdsrLinTrigger, k, kiiiiii  ktrigger, iamp, iatk, idec, islev, istime, irel xin    ktrigger limit ktrigger, 0, 1  klasttrigger init 0  if (klasttrigger == 0 &amp;&amp; ktrigger == 1) then    kstart = 1  else    kstart = 0  endif  reset:  if (kstart &lt; 1) goto contin  reinit resetcontin:  kenv linseg 0, iatk, 1, idec, islev, istime, islev, irel, 0  rireturn  kenv = iamp*kenv    klasttrigger = ktrigger      xout kenvendop  </opcode></modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/amps mixers/CrossFader.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="CrossFader" description="Crossfade between two audio signals">
  <input>
    <vardef name="in1" csType="a" description="First audio rate signal"/>
    <vardef name="in2" csType="a" description="Second audio rate signal"/>
    <vardef name="fade" csType="k" value="0" min="0" max="1" description="Crossfade between in1 (fade=0) and in2 (fade=1)"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="Mixed input signals"/>
  </output>
  <opcode>/* Crossfade between two audio signals */
opcode CrossFader, a, aak
  ain1, ain2, kfade  xin
  kfade  limit  kfade, 0, 1
  aout = ain1*(1-kfade) + ain2*kfade
  xout aout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/sound sources/SineVco.xml
<?xml version="1.0" encoding="UTF-8"?><modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="SineVco" description="Sine oscillator (amplitude 1)">  <input>    <vardef name="frq" csType="k" min="0" description="Frequency of oscillator"/>  </input>  <output>    <vardef name="out" csType="a" description="Output of oscillator (amplitude 1)"/>  </output>  <global>    <def description="Sine table">gisinevco   ftgen  0, 0, 4096, 10, 1</def>  </global>  <opcode>/* Sine oscillator */opcode SineVco, a, k  kfrq xin  kfrq     limit      kfrq, 0, 50000  asig     oscil      1, kfrq, gisinevco  xout asigendop  </opcode></modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/amps mixers/Mixer4.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="Mixer4" description="Mixer for four audio signals">
  <input>
    <vardef name="in1" csType="a" description="First audio rate signal"/>
    <vardef name="gain1" csType="k" value="1" min="0" description="Amplitude multiplicator for in1"/>
    <vardef name="in2" csType="a" description="Second audio rate signal"/>
    <vardef name="gain2" csType="k" value="1" min="0" description="Amplitude multiplicator for in2"/>
    <vardef name="in3" csType="a" description="Third audio rate signal"/>
    <vardef name="gain3" csType="k" value="1" min="0" description="Amplitude multiplicator for in3"/>
    <vardef name="in4" csType="a" description="Fourth audio rate signal"/>
    <vardef name="gain4" csType="k" value="1" min="0" description="Amplitude multiplicator for in4"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="Mixed input signals"/>
  </output>
  <opcode>/* Mixer for four audio signals */
opcode Mixer4, a, akakakak
  ain1, kgain1, ain2, kgain2, ain3, kgain3, ain4, kgain4 xin
  aout = ain1*kgain1 + ain2*kgain2 + ain3*kgain3 + ain4*kgain4
  xout aout
endop
  </opcode>
</modul>
