=== nrad/Pythonia/Cable/cabel-0.85/modules/modul.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Matthias (paprosoft) --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">	<xs:element name="modul">		<xs:annotation>			<xs:documentation>encapsulates a modul</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:sequence>				<xs:element name="input" minOccurs="0">					<xs:complexType>						<xs:sequence minOccurs="0" maxOccurs="unbounded">							<xs:element ref="vardef" minOccurs="0" maxOccurs="unbounded"/>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="output" minOccurs="0">					<xs:complexType>						<xs:sequence minOccurs="0" maxOccurs="unbounded">							<xs:element ref="vardef" minOccurs="0" maxOccurs="unbounded"/>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element name="global" minOccurs="0">					<xs:complexType>						<xs:sequence minOccurs="0">							<xs:element name="def" minOccurs="0" maxOccurs="unbounded">								<xs:complexType>									<xs:simpleContent>										<xs:extension base="xs:string">											<xs:attribute name="description" type="xs:string" use="optional"/>										</xs:extension>									</xs:simpleContent>								</xs:complexType>							</xs:element>						</xs:sequence>					</xs:complexType>				</xs:element>				<xs:element ref="opcode" minOccurs="0"/>			</xs:sequence>			<xs:attribute name="file" type="xs:string" use="optional"/>			<xs:attribute ref="name" type="xs:string" use="required"/>			<xs:attribute ref="widget" use="optional"/>			<xs:attribute ref="description" use="required"/>			<xs:attribute name="skin" type="xs:string" use="optional"/>		</xs:complexType>	</xs:element>	<xs:element name="input">		<xs:annotation>			<xs:documentation>encapsulates all input params</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:sequence minOccurs="0" maxOccurs="unbounded">				<xs:element ref="varref" minOccurs="0" maxOccurs="unbounded"/>			</xs:sequence>		</xs:complexType>	</xs:element>	<xs:element name="output">		<xs:annotation>			<xs:documentation>encapsulates all out parameters</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:choice>				<xs:element name="vardef" minOccurs="0">					<xs:complexType>						<xs:attribute name="name" type="xs:ID" use="required"/>						<xs:attribute name="csType" use="optional">							<xs:simpleType>								<xs:restriction base="xs:string">									<xs:enumeration value="i"/>									<xs:enumeration value="a"/>									<xs:enumeration value="k"/>									<xs:enumeration value="gi"/>									<xs:enumeration value="ga"/>									<xs:enumeration value="gk"/>									<xs:enumeration value="p"/>									<xs:enumeration value="v"/>									<xs:enumeration value="w"/>									<xs:enumeration value="c"/>									<xs:enumeration value="f"/>									<xs:enumeration value="gv"/>									<xs:enumeration value="fa"/>									<xs:enumeration value="reserved_symbol"/>								</xs:restriction>							</xs:simpleType>						</xs:attribute>						<xs:attribute name="description" type="xs:string" use="optional"/>					</xs:complexType>				</xs:element>				<xs:element ref="varref" minOccurs="0"/>			</xs:choice>		</xs:complexType>	</xs:element>	<xs:element name="opcode">		<xs:annotation>			<xs:documentation>calls a CSound "function"</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:simpleContent>				<xs:extension base="xs:string"/>			</xs:simpleContent>		</xs:complexType>	</xs:element>	<xs:element name="vardef">		<xs:annotation>			<xs:documentation>defines a var</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:attribute ref="name" use="required"/>			<xs:attribute name="widget" use="optional">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="defSlider"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>			<xs:attribute name="scoParam" type="xs:int" use="optional"/>			<xs:attribute name="value" type="xs:string" use="optional"/>			<xs:attribute name="min" type="xs:integer" use="optional"/>			<xs:attribute name="max" type="xs:integer" use="optional"/>			<xs:attribute ref="description" use="optional"/>			<xs:attribute name="isModulPort" type="xs:boolean" use="optional" default="1"/>			<xs:attribute name="csType" use="required">				<xs:simpleType>					<xs:restriction base="xs:string">						<xs:enumeration value="i"/>						<xs:enumeration value="a"/>						<xs:enumeration value="k"/>						<xs:enumeration value="gi"/>						<xs:enumeration value="ga"/>						<xs:enumeration value="gk"/>						<xs:enumeration value="p"/>						<xs:enumeration value="v"/>						<xs:enumeration value="w"/>						<xs:enumeration value="c"/>						<xs:enumeration value="f"/>						<xs:enumeration value="gv"/>						<xs:enumeration value="fa"/>						<xs:enumeration value="reserved_symbol"/>					</xs:restriction>				</xs:simpleType>			</xs:attribute>		</xs:complexType>	</xs:element>	<xs:element name="varref">		<xs:annotation>			<xs:documentation>references a var</xs:documentation>		</xs:annotation>		<xs:complexType>			<xs:attribute name="ref" type="xs:IDREF" use="required"/>		</xs:complexType>	</xs:element>	<xs:attribute name="widget">		<xs:annotation>			<xs:documentation>defines the widget to use for the graphical representation of the i/o params</xs:documentation>		</xs:annotation>		<xs:simpleType>			<xs:restriction base="xs:string">				<xs:enumeration value="defSlidebars"/>				<xs:enumeration value="defModulBox"/>			</xs:restriction>		</xs:simpleType>	</xs:attribute>	<xs:attribute name="name" type="xs:ID">		<xs:annotation>			<xs:documentation>unique name</xs:documentation>		</xs:annotation>	</xs:attribute>	<xs:attribute name="description" type="xs:string">		<xs:annotation>			<xs:documentation>describes the modul, var, or what it should describe.oh my god</xs:documentation>		</xs:annotation>	</xs:attribute>	<xs:attribute name="moduleID" type="xs:string">		<xs:annotation>			<xs:documentation>reference to the module to which the node belongs</xs:documentation>		</xs:annotation>	</xs:attribute></xs:schema>

=== nrad/Pythonia/Cable/cabel-0.85/modules/filters/Formant.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="Formant" description="Formant filter (be careful with amplitude of output)">
  <input>
    <vardef name="in" csType="a" description="Audio rate input"/>
    <vardef name="fcf" csType="k" value="2000" min="0" description="Filter center frequency"/>
    <vardef name="atk" csType="k" value="0.01" min="0" max="100" description="Impulse response attack time in seconds"/>
    <vardef name="dec" csType="k" value="0.003" min="0" max="100" description="Impulse response decay time in seconds"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="Filtered audio signal"/>
  </output>
  <opcode>/* Formant filter */
opcode Formant, a, akkk
  ain, kfcf, katk, kdec  xin

  kfcf    limit kfcf, 0, 50000
  katk    limit katk, 0, 100
  kdec    limit kdec, 0, 100
  aout    fofilter ain, kfcf, katk, kdec

  xout aout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/control/NoteQuantizer.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="NoteQuantizer" description="Quantize the incoming midi note numbers to selected pitches">
  <input>
    <vardef name="in" csType="k" description="Input signal"/>
    <vardef name="c" csType="k" value="1" min="0" max="1" digits="0" description="Select c"/>
    <vardef name="cis" csType="k" value="1" min="0" max="1" digits="0" description="Select cis"/>
    <vardef name="d" csType="k" value="1" min="0" max="1" digits="0" description="Select d"/>
    <vardef name="dis" csType="k" value="1" min="0" max="1" digits="0" description="Select dis"/>
    <vardef name="e" csType="k" value="1" min="0" max="1" digits="0" description="Select e"/>
    <vardef name="f" csType="k" value="1" min="0" max="1" digits="0" description="Select f"/>
    <vardef name="fis" csType="k" value="1" min="0" max="1" digits="0" description="Select fis"/>
    <vardef name="g" csType="k" value="1" min="0" max="1" digits="0" description="Select g"/>
    <vardef name="gis" csType="k" value="1" min="0" max="1" digits="0" description="Select gis"/>
    <vardef name="a" csType="k" value="1" min="0" max="1" digits="0" description="Select a"/>
    <vardef name="ais" csType="k" value="1" min="0" max="1" digits="0" description="Select ais"/>
    <vardef name="b" csType="k" value="1" min="0" max="1" digits="0" description="Select b"/>
  </input>
  <output>
    <vardef name="out" csType="k" description="Quantized input signal"/>
  </output>
  <opcode>/* Quantize  the incoming midi note numbers to selected pitches */
opcode NoteQuantizer, k, kkkkkkkkkkkkk
  kin, kc, kcis, kd, kdis, ke, kf, kfis, kg, kgis, ka, kais, kb xin

  kin     limit    kin, 0, 127
  kin     =        int(kin)

  kc      limit    kc, 0, 1
  kc      =        int(kc)
  kcis    limit    kcis, 0, 1
  kcis    =        int(kcis)
  kd      limit    kd, 0, 1
  kd      =        int(kd)
  kdis    limit    kdis, 0, 1
  kdis    =        int(kdis)
  ke      limit    ke, 0, 1
  ke      =        int(ke)
  kf      limit    kf, 0, 1
  kf      =        int(kf)
  kfis    limit    kfis, 0, 1
  kfis    =        int(kfis)
  kg      limit    kg, 0, 1
  kg      =        int(kg)
  kgis    limit    kgis, 0, 1
  kgis    =        int(kgis)
  ka      limit    ka, 0, 1
  ka      =        int(ka)
  kais    limit    kais, 0, 1
  kais    =        int(kais)
  kb      limit    kb, 0, 1
  kb      =        int(kb)

  kout    init     0
  
  knote   =        kin%12
  kset    =        0

  kskip   = kc+kcis+kd+kdis+ke+kf+kfis+kg+kgis+ka+kais+kb
  if (kskip == 0) goto skip

restart:
  if (knote == 0 &amp;&amp; kc == 1) then
    kout = kin
    kset = 1
  elseif (knote == 1 &amp;&amp; kcis == 1) then
    kout = kin
    kset = 1
  elseif (knote == 2 &amp;&amp; kd == 1) then
    kout = kin
    kset = 1
  elseif (knote == 3 &amp;&amp; kdis == 1) then
    kout = kin
    kset = 1
  elseif (knote == 4 &amp;&amp; ke == 1) then
    kout = kin
    kset = 1
  elseif (knote == 5 &amp;&amp; kf == 1) then
    kout = kin
    kset = 1
  elseif (knote == 6 &amp;&amp; kfis == 1) then
    kout = kin
    kset = 1
  elseif (knote == 7 &amp;&amp; kg == 1) then
    kout = kin
    kset = 1
  elseif (knote == 8 &amp;&amp; kgis == 1) then
    kout = kin
    kset = 1
  elseif (knote == 9 &amp;&amp; ka == 1) then
    kout = kin
    kset = 1
  elseif (knote == 10 &amp;&amp; kais == 1) then
    kout = kin
    kset = 1
  elseif (knote == 11 &amp;&amp; kb == 1) then
    kout = kin
    kset = 1
  endif
  
  kin = kin + 1
  knote = kin%12
  if (kset == 0) goto restart

skip:
  xout kout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/maths/ControlLimit.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="ControlLimit" description="Limit signal to range from min to max">
  <input>
    <vardef name="in" csType="k" description="Input signal"/>
    <vardef name="min" value="0" csType="k" description="Minimal allowed signal"/>
    <vardef name="max" value="100" csType="k" description="Maximal allowed signal"/>
  </input>
  <output>
    <vardef name="out" csType="k" description="Limited signal"/>
  </output>
  <opcode>/* Limit signal to range from min to max */
opcode ControlLimit, k, kkk
  kin, kmin, kmax xin
  kout limit kin, kmin, kmax
  xout kout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/modulators/PulseLfo.xml
<?xml version="1.0" encoding="UTF-8"?><modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="PulseLfo" description="Pulse low frequency oscillator (clock signal)">  <input>    <vardef name="frq" csType="k" value="10" min="0" max="100" description="Frequency of LFO"/>    <vardef name="amp" csType="k" value="1" min="0" description="Amplitude of LFO"/>    <vardef name="phi" csType="i" value="0" min="-0.001" max="1" digits="3" description="Initial phase of LFO (negativ to skip initialisation)"/>  </input>  <output>    <vardef name="out" csType="k" description="Output of LFO"/>  </output>  <global>    <def description="Pulse table">gipulselfo   ftgen  0, 0, 128, -7, 1, 4, 1, 0, 0, 124, 0</def>  </global>  <opcode>/* Pulse low frequency oscillator (clock signal) */opcode PulseLfo, k, kki  kfrq, kamp, iphi xin  kfrq     limit      kfrq, 0, 100  kamp     limit      kamp, 0, 50000  iphi     limit      iphi, -1, 1  kout     oscil      kamp, kfrq, gipulselfo, iphi  xout koutendop  </opcode></modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/filters/ButterBp.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="ButterBp" description="A second-order band-pass Butterworth filter">
  <input>
    <vardef name="in" csType="a" description="Audio rate input"/>
    <vardef name="fcf" csType="k" value="2000" min="0" description="Filter center frequency"/>
    <vardef name="bandwidth" csType="k" value="100" min="0" description="Bandwidth of the filter"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="Filtered audio signal"/>
  </output>
  <opcode>/* Second-order Butterworth band-pass filter */
opcode ButterBp, a, akk
  ain, kfcf, kbandwidth  xin

  kfcf    limit kfcf, 0, 50000
  kbandwidth limit kbandwidth, 0, 50000
  aout    butterbp ain, kfcf, kbandwidth

  xout aout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/filters/MoogVcf.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="MoogVcf" description="Moog lowpass filter, to avoid clipping use input signal with max amplitude 1">
  <input>
    <vardef name="in" csType="a" min="-1" max="1" description="Audio rate input, to avoid clipping use input signal with max amplitude 1"/>
    <vardef name="fco" csType="k" value="2000" min="0" description="Filter cut-off frequency"/>
    <vardef name="res" csType="k" min="0" max="2" description="Filter resonance (self-resonates at 1)"/>
  </input>
  <output>
    <vardef name="out" csType="a" description="Filtered audio signal"/>
  </output>
  <opcode>/* Moog lowpass filter */
opcode MoogVcf, a, akk
  ain, kfco, kres  xin

  ain     limit ain, -1, 1
  kfco    limit kfco, 0, 50000
  kres    limit kres, 0, 2
  aout    moogvcf ain, kfco, kres

  xout aout
endop
  </opcode>
</modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/modulators/Lfo.xml
<?xml version="1.0" encoding="UTF-8"?><modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="Lfo" description="Low frequency oscilllator with multiple waveform types">  <input>    <vardef name="frq" csType="k" value="1" min="0" max="400" description="Frequency of LFO"/>    <vardef name="amp" csType="k" value="1" min="0" description="Amplitude of LFO"/>    <vardef name="waveform" csType="i" value="0" min="0" max="5" digits="0" description="Output Waveform: 0 sine, 1 trinangle, 2 square (bipolar), 3 square (unipolar), 4 ramp, 5 saw"/>  </input>  <output>    <vardef name="out" csType="k" description="Output of LFO"/>  </output>  <opcode>/* LFO with multiple waveforms */opcode Lfo, k, kki  kfrq, kamp, iwaveform xin  kfrq     limit      kfrq, 0, 100  kamp     limit      kamp, 0, 50000  kout     lfo        kamp, kfrq, iwaveform  xout koutendop  </opcode></modul>

=== nrad/Pythonia/Cable/cabel-0.85/modules/control/MidiNoteMonoGlideIn.xml
<?xml version="1.0" encoding="UTF-8"?>
<modul xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modul.xsd" name="MidiNoteMonoGlideIn" description="Midi note input for monosynth with portamento">
  <input>
    <vardef name="velscale" csType="i" value="15000" min="0" max="32000" description="Scaling of MIDI velocity"/>
    <vardef name="minafttch" csType="i" value="0" description="Minimal value for scaled channel aftertouch"/>
    <vardef name="maxafttch" csType="i" value="127" description="Maximal value for scaled channel aftertouch"/>
    <vardef name="portatime" csType="i" value="0.05" min="0.001" max="100" description="Portamento time in seconds"/>
  </input>
  <output>
    <vardef name="frq" csType="k" description="Frequency of MIDI note with pitch bend information"/>
    <vardef name="note" csType="k" description="MIDI note number of last pressed key"/>
    <vardef name="vel" csType="i" description="Velocity of MIDI note"/>
    <vardef name="afttch" csType="k" description="Scaled channel aftertouch"/>
  </output>
  <global>
    <def description="Number of instruments">gkcntmidinotemonoglidein init 0</def>
    <def description="Old pitch of instruments">giptchmidinotemonoglidein init 200</def>
  </global>
  <opcode>/* Midi note input for monosynth with portamento */
opcode MidiNoteMonoGlideIn, kkik, iiii

  icnt                =    i(gkcntmidinotemonoglidein)+1
  gkcntmidinotemonoglidein init icnt

  /* Turn instrument off if there's a new instance */
  if (icnt &lt; gkcntmidinotemonoglidein) then
    turnoff     
  endif

  ivelscale, iminafttch, imaxafttch, iportatime xin

  knote init 0
  kvel init 0
  kafttch init 0
  kptchbnd init 0

  midinoteonkey knote, kvel
  midichannelaftertouch kafttch, iminafttch, imaxafttch
  midipitchbend kptchbnd
  ifrq cpsmidi
  ivel ampmidi  ivelscale

  /* Add portamento to frequency */
  kglide expseg giptchmidinotemonoglidein, iportatime, ifrq, 1, ifrq
  giptchmidinotemonoglidein = ifrq
  kfrq = kglide

  /* Add pitchbend (-1 octave to +1 octave) */
  kfrq = kfrq * 2^kptchbnd

  xout kfrq, knote, ivel, kafttch
endop
  </opcode>
</modul>
